### ISSUE TITLE
[native-image] does not print result corect result of scr:list 

### ISSUE THREAD

**Issue by stbischof** [tjwatson/atomos#22]
Graal Version: graalvm-ce-java11-19.3.1

Result:
```
g! scr:list
{}
{}
{}
{}
{}
```

**Comment by gurkerl83** [comment]
Hi, a few days ago I also tried to upgrade do graal 19.3.1. If I remember correctly the other commands were working as expected, except this one. Was scr:list even working before?

**Comment by stbischof** [comment]
scr:list  prints out a the dto's of the scr.

org.osgi.dto.DTO:toString calls this. Maybe we have some issues to get the fields of the dto


private static StringBuilder appendDTO(final StringBuilder result, final Map<Object, String> objectRefs, final String refpath, final DTO dto) {
        result.append("{");
        String delim = "";
        for (Field field : dto.getClass().getFields()) {
            if (Modifier.isStatic(field.getModifiers())) {
                continue;
            }
            result.append(delim);
            final String name = field.getName();
            appendString(result, name);
            result.append(":");
            Object value = null;
            try {
                value = field.get(dto);
            } catch (IllegalAccessException e) {
                // use null value;
            }
            appendValue(result, objectRefs, refpath + "/" + name, value);
            delim = ", ";
        }
        result.append("}");
        return result;
    }

**Comment by stbischof** [comment]
Best way  would be that felix removes proxy and loding via classpath and ship's  3 bundles
* Scr without gogo
* Scr gogo commands
* Scr with gogo commands

We may should do the same with  atomos.

**Comment by tjwatson** [comment]
I think we should be able to configure `org.apache.felix.service.command.Converter` as a proxy config.  For the felix SCR to work with the felix framework substrate example we had to add that.  We can try to add the same for the equinox example to see if it fixes the issue.

**Comment by tjwatson** [comment]
I tried adding the proxy config to your changes in PR #25 but it didn't seem to help.

**Comment by stbischof** [comment]
it helps!

**Comment by tjwatson** [comment]
The substrate example with felix framework works for scr:list so something there in the substrate config makes it work.  I may have messed up in my try with Equinox.

**Comment by stbischof** [comment]
3 Things are missing. now it works with equinox.
I will make a PR

* `graal_proxy_config.json`
```
[
  ["org.apache.felix.service.command.Converter"]
]
```
 ------
`graal_class_config.json`
```
 {
     "name":"org.apache.felix.service.command.Converter"
  },
```
----

`pom.xml` 

```
	<plugin>
				<groupId>org.graalvm.nativeimage</groupId>
				<artifactId>native-image-maven-plugin</artifactId>
				...
				<configuration>
						--initialize-at-build-time=...,org.apache.felix.service.command.Converter
				-H:ReflectionConfigurationFiles=${project.basedir}/graal_class_config.json
				-H:ResourceConfigurationFiles=${project.basedir}/graal_resource_config.json
...
					-H:+PrintClassInitialization
					</buildArgs>
				</configuration>
			</plugin>
```

**Comment by tjwatson** [comment]
Fixed now.
