### ISSUE TITLE
Give the test bundles a better project structure

### ISSUE THREAD

**Issue by stbischof** [tjwatson/atomos#25]
When i first had a look into the test it wasn't easy for me to know what this maven projects in the test-folder are for.

It would be much easier to have it like this.

* atomos.tests
	* classpath.service.test
	* modulepath.service.test
	* substrate.service.test (service.substrate)
	* test-resources
		* resources.a
		* service.contract 
		* service.image
		* service.impl.a
		* service.impl.activator
		* service.impl.b
		* service.impl
		* service.lib
		* service.user

Is it ok to refactor it?

**Comment by tjwatson** [comment]
Yes I think this is a good direction.  I would probably call it `test-bundles` instead of `test-resources`

**Comment by tjwatson** [comment]
For service.substrate and service.image we should have a separate folder that is a peer to `atomos.tests` called `atomos.examples` and I would rename `service.substrate`->`atomos.substrate.example` and `service.image` -> `atomos.jlink.example`

* atomos.examples
	* atomos.jlink.example
	* atomos.substrate.example

**Comment by tjwatson** [comment]
I'll work on the atomos.examples structure because I am in the middle of getting felix Framework up and running with Atomos and need to make some changes to the examples anyway.

**Comment by tjwatson** [comment]
I finished the move of examples.  We now have the following in master:

* atomos.examples
	* atomos.examples.jlink
	* atomos.examples.substrate.equinox
	* atomos.examples.substrate.felix

All use the group ID `atomos.examples`.  Only the example `atomos.examples.jlink` builds by default.  The workflow will also build `atomos.examples.substrate.equinox` but I don't have it building `atomos.examples.substrate.felix` at the moment.  I don't see the need to build it right now without any additional verification just yet.

**Comment by stbischof** [comment]
> All use the group ID atomos.examples.

group ID is  `org.atomos.examples`. Is that just a type here or wrong group id in pom?

**Comment by tjwatson** [comment]
opps, yes that was a typo, the group ID of the examples is `org.atomos.examples`

**Comment by tjwatson** [comment]
I would prefer we use `org.atomos.test` as the group ID for test projects and `org.atomos.test.bundles` as the group ID for the test bundles.
