### ISSUE TITLE
/lib in .gitignore

### ISSUE THREAD

**Issue by stbischof** [tjwatson/atomos#27]
@tjwatson 
Im not sure how you could commit the files in this folder:

https://github.com/tjwatson/atomos/tree/master/atomos.tests/service.lib/src/main/java/org/atomos/service/lib

with this commit:

https://github.com/tjwatson/atomos/commit/7e020854631f284b29ccf872a11cca9639ed029e

because there is a .gitignore for /lib folders.

https://github.com/tjwatson/atomos/blob/afd8f6741e89d389e302958779f6c3d8738da309/.gitignore#L31

i would rename the package  to `library` to fix that

**Comment by tjwatson** [comment]
I must have either committed before the `.gitignore` or perhaps used a -f option for git add.  Yes, renaming the package probably is best.

**Comment by tjwatson** [comment]
Fixed now.
