### ISSUE TITLE
format pom.xml 

### ISSUE THREAD

**Issue by stbischof** [tjwatson/atomos#28]
some of the pom files uses tabs, some whitespaces and other are mixed. It would be nice to know in which way.

Indent using whitespaces
line width 72
clear all blank lines
format comments (join lines)
Identation size 2

**Comment by tjwatson** [comment]
I don't have a strong preference.  I've been using the default formatting in Eclipse for the Maven pom editor which seems to use tabs for indent.  But admit that I haven't been good on making sure I run the formatting after doing copy/paste from some example pom.  I am not a big fan of limiting line width something as small as 72.
