### ISSUE TITLE
Equinox substrate atomos bundle.index needs fixed after test bundle refactoring

### ISSUE THREAD

**Issue by tjwatson** [tjwatson/atomos#29]
Unfortunately to test out the atomos `bundle.index` for substrate the `atomos.examples.substrate.equinox` project has some copies of resources from test bundles.  These need to be updated now that the test bundles have been refactored.  The folder `/atomos.examples.substrate.equinox/src/main/resources/atomos` needs to be regenerated for the set of bundles included in the image.

**Comment by stbischof** [comment]
Oh Sorry. I will fix this.

**Comment by tjwatson** [comment]
No need, I fixed it already.

I did update `/atomos.examples.substrate.equinox/pom.xml` to copy the bundles of the image into a `classpath_lib` folder

This at least makes it a little bit easier to generate the `atomos/bundles.index` by starting with classpath mode with the set of bundles:

`java -cp "atomos.examples.substrate.equinox-0.0.1-SNAPSHOT.jar:classpath_lib/*" org.atomos.examples.substrate.equinox.GogoConsole`

And then running the gogo command:

`atomos:substrateBundles <path to atomos>/atomos/atomos.examples/atomos.examples.substrate.equinox/src/main/resources`
