### ISSUE TITLE
Native image build failure

### ISSUE THREAD

**Issue by gurkerl83** [tjwatson/atomos#3]
Hi, first of all its great to see OSGi going AOT. I followed the build instructions for Substrate.

1. Built atomos with latest JDK 11 (jdk-11.0.5.jdk)
2. Switched to Graal (graalvm-ce-19.2.1)
3. Executed mvn clean package from the Substrate example folder

Step 3 throws the following build error saying

Error opening zip file or JAR manifest missing : null
Error occurred during initialization of VM
agent library failed to init: instrument

Are the instructions still valid, I think so, because graal is currently not shipping JDK11, maybe in the upcoming release.

Maybe you saw this error, and give some hint what I do wrong.

Thx!

Step 3 build output
[INFO] --- native-image-maven-plugin:19.2.0.1:native-image (default) @ service.substrate ---
[INFO] ImageClasspath Entry: org.eclipse.platform:org.eclipse.osgi:jar:3.16.0.tjwatson_osgiConnect01:compile (file:///Users/markusgritsch/.m2/repository/org/eclipse/platform/org.eclipse.osgi/3.16.0.tjwatson_osgiConnect01/org.eclipse.osgi-3.16.0.tjwatson_osgiConnect01.jar)
[INFO] ImageClasspath Entry: org.atomos:atomos.framework:jar:0.0.1-SNAPSHOT:compile (file:///Users/markusgritsch/.m2/repository/org/atomos/atomos.framework/0.0.1-SNAPSHOT/atomos.framework-0.0.1-SNAPSHOT.jar)
[INFO] ImageClasspath Entry: org.atomos:service.contract:jar:0.0.1-SNAPSHOT:compile (file:///Users/markusgritsch/.m2/repository/org/atomos/service.contract/0.0.1-SNAPSHOT/service.contract-0.0.1-SNAPSHOT.jar)
[INFO] ImageClasspath Entry: org.atomos:service.impl:jar:0.0.1-SNAPSHOT:compile (file:///Users/markusgritsch/.m2/repository/org/atomos/service.impl/0.0.1-SNAPSHOT/service.impl-0.0.1-SNAPSHOT.jar)
[INFO] ImageClasspath Entry: org.osgi:org.osgi.service.component.annotations:jar:1.4.0:compile (file:///Users/markusgritsch/.m2/repository/org/osgi/org.osgi.service.component.annotations/1.4.0/org.osgi.service.component.annotations-1.4.0.jar)
[INFO] ImageClasspath Entry: org.atomos:service.impl.activator:jar:0.0.1-SNAPSHOT:compile (file:///Users/markusgritsch/.m2/repository/org/atomos/service.impl.activator/0.0.1-SNAPSHOT/service.impl.activator-0.0.1-SNAPSHOT.jar)
[INFO] ImageClasspath Entry: org.apache.felix:org.apache.felix.scr:jar:2.1.16:compile (file:///Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.scr/2.1.16/org.apache.felix.scr-2.1.16.jar)
[INFO] ImageClasspath Entry: org.codehaus.mojo:animal-sniffer-annotations:jar:1.9:compile (file:///Users/markusgritsch/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.9/animal-sniffer-annotations-1.9.jar)
[INFO] ImageClasspath Entry: org.osgi:osgi.promise:jar:7.0.1:compile (file:///Users/markusgritsch/.m2/repository/org/osgi/osgi.promise/7.0.1/osgi.promise-7.0.1.jar)
[INFO] ImageClasspath Entry: org.apache.felix:org.apache.felix.gogo.command:jar:1.1.0:compile (file:///Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.gogo.command/1.1.0/org.apache.felix.gogo.command-1.1.0.jar)
[INFO] ImageClasspath Entry: org.apache.felix:org.apache.felix.gogo.runtime:jar:1.1.2:compile (file:///Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.gogo.runtime/1.1.2/org.apache.felix.gogo.runtime-1.1.2.jar)
[INFO] ImageClasspath Entry: org.apache.felix:org.apache.felix.gogo.shell:jar:1.1.2:runtime (file:///Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.gogo.shell/1.1.2/org.apache.felix.gogo.shell-1.1.2.jar)
[INFO] ImageClasspath Entry: org.apache.felix:org.apache.felix.http.jetty:jar:3.1.0.substrate:compile (file:///Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.http.jetty/3.1.0.substrate/org.apache.felix.http.jetty-3.1.0.substrate.jar)
[INFO] ImageClasspath Entry: org.apache.felix:org.apache.felix.http.api:jar:3.0.0:compile (file:///Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.http.api/3.0.0/org.apache.felix.http.api-3.0.0.jar)
[INFO] ImageClasspath Entry: org.apache.felix:org.apache.felix.http.whiteboard:jar:3.0.0:compile (file:///Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.http.whiteboard/3.0.0/org.apache.felix.http.whiteboard-3.0.0.jar)
[INFO] ImageClasspath Entry: org.apache.felix:org.apache.felix.webconsole:jar:all:4.3.16:compile (file:///Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.webconsole/4.3.16/org.apache.felix.webconsole-4.3.16-all.jar)
[INFO] ImageClasspath Entry: org.apache.felix:org.apache.felix.http.servlet-api:jar:1.1.2:compile (file:///Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.http.servlet-api/1.1.2/org.apache.felix.http.servlet-api-1.1.2.jar)
[INFO] ImageClasspath Entry: org.apache.tomcat:tomcat-servlet-api:jar:8.0.9:compile (file:///Users/markusgritsch/.m2/repository/org/apache/tomcat/tomcat-servlet-api/8.0.9/tomcat-servlet-api-8.0.9.jar)
[INFO] ImageClasspath Entry: org.osgi:org.osgi.service.cm:jar:1.5.0:compile (file:///Users/markusgritsch/.m2/repository/org/osgi/org.osgi.service.cm/1.5.0/org.osgi.service.cm-1.5.0.jar)
[INFO] ImageClasspath Entry: org.osgi:org.osgi.service.event:jar:1.4.0:compile (file:///Users/markusgritsch/.m2/repository/org/osgi/org.osgi.service.event/1.4.0/org.osgi.service.event-1.4.0.jar)
[INFO] ImageClasspath Entry: org.atomos:service.substrate:jar:0.0.1-SNAPSHOT (file:///Users/markusgritsch/Development/Topics/Graal/OSGi/atomos/atomos.tests/service.substrate/target/service.substrate-0.0.1-SNAPSHOT.jar)
[INFO] WorkingDirectory: /Users/markusgritsch/Development/Topics/Graal/OSGi/atomos/atomos.tests/service.substrate/target
[INFO] ImageClasspath: /Users/markusgritsch/.m2/repository/org/eclipse/platform/org.eclipse.osgi/3.16.0.tjwatson_osgiConnect01/org.eclipse.osgi-3.16.0.tjwatson_osgiConnect01.jar:/Users/markusgritsch/.m2/repository/org/atomos/atomos.framework/0.0.1-SNAPSHOT/atomos.framework-0.0.1-SNAPSHOT.jar:/Users/markusgritsch/.m2/repository/org/atomos/service.contract/0.0.1-SNAPSHOT/service.contract-0.0.1-SNAPSHOT.jar:/Users/markusgritsch/.m2/repository/org/atomos/service.impl/0.0.1-SNAPSHOT/service.impl-0.0.1-SNAPSHOT.jar:/Users/markusgritsch/.m2/repository/org/osgi/org.osgi.service.component.annotations/1.4.0/org.osgi.service.component.annotations-1.4.0.jar:/Users/markusgritsch/.m2/repository/org/atomos/service.impl.activator/0.0.1-SNAPSHOT/service.impl.activator-0.0.1-SNAPSHOT.jar:/Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.scr/2.1.16/org.apache.felix.scr-2.1.16.jar:/Users/markusgritsch/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.9/animal-sniffer-annotations-1.9.jar:/Users/markusgritsch/.m2/repository/org/osgi/osgi.promise/7.0.1/osgi.promise-7.0.1.jar:/Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.gogo.command/1.1.0/org.apache.felix.gogo.command-1.1.0.jar:/Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.gogo.runtime/1.1.2/org.apache.felix.gogo.runtime-1.1.2.jar:/Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.gogo.shell/1.1.2/org.apache.felix.gogo.shell-1.1.2.jar:/Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.http.jetty/3.1.0.substrate/org.apache.felix.http.jetty-3.1.0.substrate.jar:/Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.http.api/3.0.0/org.apache.felix.http.api-3.0.0.jar:/Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.http.whiteboard/3.0.0/org.apache.felix.http.whiteboard-3.0.0.jar:/Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.webconsole/4.3.16/org.apache.felix.webconsole-4.3.16-all.jar:/Users/markusgritsch/.m2/repository/org/apache/felix/org.apache.felix.http.servlet-api/1.1.2/org.apache.felix.http.servlet-api-1.1.2.jar:/Users/markusgritsch/.m2/repository/org/apache/tomcat/tomcat-servlet-api/8.0.9/tomcat-servlet-api-8.0.9.jar:/Users/markusgritsch/.m2/repository/org/osgi/org.osgi.service.cm/1.5.0/org.osgi.service.cm-1.5.0.jar:/Users/markusgritsch/.m2/repository/org/osgi/org.osgi.service.event/1.4.0/org.osgi.service.event-1.4.0.jar:/Users/markusgritsch/Development/Topics/Graal/OSGi/atomos/atomos.tests/service.substrate/target/service.substrate-0.0.1-SNAPSHOT.jar
[INFO] BuildArgs: [-Dosgi.connect.substrate=/Users/markusgritsch/Development/Topics/Graal/OSGi/atomos/atomos.tests/service.substrate/target, -H:+ReportUnsupportedElementsAtRuntime, --allow-incomplete-classpath, --no-fallback, -H:ReflectionConfigurationFiles=/Users/markusgritsch/Development/Topics/Graal/OSGi/atomos/atomos.tests/service.substrate/graal_class_config.json, -H:ResourceConfigurationFiles=/Users/markusgritsch/Development/Topics/Graal/OSGi/atomos/atomos.tests/service.substrate/graal_resource_config.json, --initialize-at-build-time=org.eclipse.osgi,org.eclipse.equinox.log,org.atomos.framework,org.osgi.framework,org.osgi.dto,org.osgi.service.condpermadmin,org.osgi.service.log,org.osgi.service.packageadmin,org.osgi.service.permissionadmin,org.osgi.service.resolver,org.osgi.service.startlevel,org.osgi.service.url,org.osgi.util.tracker,org.osgi.resource,org.apache.felix.resolver,javax.servlet, -H:+ReportExceptionStackTraces, -H:+TraceClassInitialization, -H:Class=org.atomos.service.substrate.GogoConsole, -H:Name=atomos]
Error opening zip file or JAR manifest missing : null
Error occurred during initialization of VM
agent library failed to init: instrument
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.478 s
[INFO] Finished at: 2019-10-29T13:27:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.oracle.substratevm:native-image-maven-plugin:19.2.0.1:native-image (default) on project service.substrate: Error creating native image:: Image build request failed with exit status 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by tjwatson** [comment]
See https://www.graalvm.org/docs/reference-manual/native-image/ for Install Native Image

You need to run the `gu` command that comes with Graal VM:

`gu install native-image`

I've updated the README in master to give these instructions.  Thanks for the interest.
