### ISSUE TITLE
Graal update

### ISSUE THREAD

**Issue by gurkerl83** [tjwatson/atomos#6]
Hi,

just read some change log of the new Graal version in a medium article (https://medium.com/graalvm/graalvm-19-3-0-dfdb6f4ec8ed). In the last commit you have increased the version of native-image-maven-plugin. The article mentions the following change 

**Maven Updates**

> Another very important change in 19.3 is the difference in the Maven coordinates for the GraalVM Native Image related jars. The group id for the artifacts is changed from com.oracle.substratevm to org.graalvm.nativeimage.

```
<plugin>
    <groupId>org.graalvm.nativeimage</groupId>
    <artifactId>native-image-maven-plugin</artifactId>
    <version>19.3.0</version>
    <executions>
        <execution>
            <goals>
                <goal>native-image</goal>
            </goals>
            <phase>package</phase>
        </execution>
    </executions>
</plugin>
```

**Comment by tjwatson** [comment]
Thanks. I somehow missed that detail in the release notes.  Updated pom to use the latest group ID and plugin version 19.3.0
